name = "colorglyph-worker"
main = "src/index.ts"
compatibility_date = "2023-10-10"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
usage_model = "unbound"

kv_namespaces = [
    { binding = "GLYPHS", id = "6904475f966746e09bc39128d73dc975" }
]

[[r2_buckets]]
binding = 'IMAGES'
bucket_name = 'colorglyph-images'

[[durable_objects.bindings]]
name = "MINT_FACTORY"
class_name = "MintFactory"

[[durable_objects.bindings]]
name = "CHANNEL_ACCOUNT"
class_name = "ChannelAccount"

[[migrations]]
tag = "v1"
new_classes = ["MintFactory", "ChannelAccount"]

[[queues.producers]]
binding = "TX_QUEUE"
queue = "colorglyph-tx-queue"

[[queues.consumers]]
queue = "colorglyph-tx-queue"
max_batch_size = 1
max_batch_timeout = 10
max_retries = 12
max_concurrency = 1

[[queues.producers]]
binding = "MINT_QUEUE"
queue = "colorglyph-mint-queue"

[[queues.consumers]]
queue = "colorglyph-mint-queue"
max_batch_size = 1
max_batch_timeout = 10
max_retries = 6
max_concurrency = 1

# Stand up a dlq for retrying failed mint jobs
# Stand up some method for dealing with unresolvable issues (e.g. secret account too low balance to keep making progress)