name = "colorglyph-worker"
main = "src/index.ts"
compatibility_date = "2023-10-10"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
usage_model = "unbound"

kv_namespaces = [
    { binding = "GLYPHS", id = "fbfea727106c4c2893fe8d03563d0387" }
]

[[r2_buckets]]
binding = 'ERRORS'
bucket_name = 'colorglyph-errors'

[[r2_buckets]]
binding = 'IMAGES'
bucket_name = 'colorglyph-images'

[[durable_objects.bindings]]
name = "CHANNEL_ACCOUNT"
class_name = "ChannelAccount"

[[durable_objects.bindings]]
name = "MINT_FACTORY"
class_name = "MintFactory"

[[migrations]]
tag = "v1"
new_classes = ["ChannelAccount", "MintFactory"]

[[migrations]]
tag = "v2"
new_classes = ["TestDo"]

[[migrations]]
tag = "v3"
deleted_classes = ["TestDo"]

[[queues.producers]]
binding = "TX_SEND"
queue = "colorglyph-tx-send"

[[queues.consumers]]
queue = "colorglyph-tx-send"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 12
max_concurrency = 1

[[queues.producers]]
binding = "TX_GET"
queue = "colorglyph-tx-get"

[[queues.consumers]]
queue = "colorglyph-tx-get"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 12
dead_letter_queue = "colorglyph-tx-get-dlq"
# max_concurrency = 20

[[queues.consumers]]
queue = "colorglyph-tx-get-dlq"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 12

# TODO Stand up a dlqs for logging failed jobs